### ISSUE TITLE
How can I get and used libnqsb-tls.so?

### ISSUE THREAD

**Issue by jnchzy** [mirleft/libnqsb-tls#10]
> Dear Sir:
> In the paper ,OCaml inside: a drop-in replacement for libtls,how can I get libnqsb-tls.so? Do I need to build sources of libnqsb-tls-master or libnqsb-tls-update-tls-and-cleanup On OpenBSD? Which version? Master or Update-tls-and-cleanup? Which version of OpenBSD? I have built libnqsb-tls-master on ubuntu14.04 successfully. In the _build directory，there is libtls.so. But when I build libnqsb-tls-master on the OpenBSD6.4, there are some errors:
> ![image](https://user-images.githubusercontent.com/20393374/55931053-99df4580-5c56-11e9-860f-8db37d6c0360.png)
> If it's not the case, are there particular notes on how to properly run tests? Maybe I've just missed some details or some passages. Thank you very much!

**Comment by yallop** [comment]
Does using `gmake` (GNU Make) rather than `make` help?
